[package]
name = "qbctld"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
qb-application = { path = "../../crates/qb-application" }
qb-domain = { path = "../../crates/qb-domain" }
anyhow.workspace = true
clap.workspace = true
prost.workspace = true
qb-ipc = { path = "../../crates/qb-ipc" }
qb-journal = { path = "../../crates/qb-journal" }
qb-proto = { path = "../../crates/qb-proto" }
qb-qbit = { path = "../../crates/qb-qbit" }
qb-win = { path = "../../crates/qb-win" }
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
