[workspace]
resolver = "2"
members = [
    "apps/qbctl",
    "apps/qbctld",
    "crates/qb-domain",
    "crates/qb-application",
    "crates/qb-proto",
    "crates/qb-ipc",
    "crates/qb-metainfo",
    "crates/qb-qbit",
    "crates/qb-journal",
    "crates/qb-win",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
publish = false

[workspace.dependencies]
anyhow = "1"
bytes = "1"
clap = { version = "4", features = ["derive"] }
fs2 = "0.4"
futures-util = { version = "0.3", features = ["sink"] }
prost = "0.14"
rusqlite = { version = "0.37", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
tempfile = "3"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util", "signal", "time", "sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
uuid = { version = "1", features = ["v4"] }

windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Security_Credentials", "Win32_Storage_FileSystem"] }
reqwest = { version = "0.13.5", default-features = false, features = ["form", "json", "query"] }
serde_json = "1"
sha1 = "0.10"
sha2 = "0.10"
urtorrent-bencode = "0.14.2"
