[package]
name = "qb-qbit"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
qb-application = { path = "../qb-application" }
qb-domain = { path = "../qb-domain" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
