[package]
name = "qb-ipc"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
futures-util.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
